name: bellshade_dart

repository: https://github.com/bellshade/Dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  coverage: ^1.0.3

dev_dependencies:
  analyzer: ^2.3.0
  lints: ^1.0.1
  stack: ^0.2.1
  test: ^1.16.5
