name: bellshade_dart

repository: https://github.com/bellshade/Dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  test: ^1.15.4
  coverage: ^0.14.1

dev_dependencies:
  lints: ^1.0.1
  pedantic: ^1.10.0
  stack: ^0.0.1